### ISSUE TITLE
Show only blocks that contains certain tags inside page and hide others 

### ISSUE THREAD

**Issue by gioknx** [mlanza/logseq-style-carousel#10]
This plugin is perfect, and I've been frying my brain trying to solve a particular case (that can be easily achieved in Roam with a filter).

With Style Carousel I can toggle certain tags "on" (show) and "off" (hide).

So if I have

- [[A]]
- [[B]]
- [[C]]

...and I have a button associated with B, I can make B disappear or come back.

But what I want is having a button associated with B, and when I press it, all blocks that does not contains [[B]] will be hidden.

Is there any way to achieve this? It'd be perfect!

Thank you very much Mr Lanza!

**Comment by mlanza** [comment]
It is certainly doable to some extent but you're always going to have edge cases and things you haven't anticipated.  In short whenever I try to get what I'm after it involves trial and error.

I'll get you started, but you're going to have to work out your own details.

Add a new button to the plugin settings:

```json
    ...
    "bee": {
      "desc": "Toggles the visibility of bee",
      "disabled": false,
      "refreshRate": 5,
      "hits": [
        "text-decoration: underline;",
        ""
      ],
      "styles": [
        {
          "tooltip": "Everything",
          "char": "\\ea69",
          "status": "everything",
          "hits": "div#main-content-container div[data-refs-self*='\"bee\"']"
        },
        {
          "tooltip": "Bee only",
          "char": "\\ea67",
          "status": "bee-only",
          "hits": "div#main-content-container div[data-refs-self*='\"bee\"']"
        },
        {
          "tooltip": "Other than bee",
          "char": "\\ea68",
          "status": "other-than-bee",
          "hits": "div#main-content-container div[data-refs-self*='\"bee\"']"
        }
      ]
    },
    ...
```

Add styles to your `custom.css`:

```css
body[data-sc-bee="bee-only"] div[data-refs-self] {
  display: none;
}
body[data-sc-bee="bee-only"] div[data-refs-self*='\"bee\"'] {
  display: inherit;
}
body[data-sc-bee="other-than-bee"] div[data-refs-self] {
  display: inherit;
}
body[data-sc-bee="other-than-bee"] div[data-refs-self*='\"bee\"'] {
  display: none;
}
```

You spoke of having a button which makes B disappear and come back.  Then you indicated interest in having another button which makes all-other-than-B disappear and come back.  This puts the two buttons at odds with each other.  Fortunately, Style Carousel was designed for more than toggling.  You have a button with three possible states.  That's what I set up for you.  Each state explains itself.

Unfortunately, the only way tweak all this involves looking under the hood.  I had to open the Developer Tools and look at the DOM to get you started.  You're going to have to do the same to consider and handle your edge cases.  There's no shortcut and no way around it.  Plus, you're going to have to CSS.  Carousel just puts the appropriate hooks in place.  The developer is still needed to determine what styles should be installed.

With Carousel and Classy you can do just about anything.  It's really a matter of your time and patience.
